name: Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Log Message host
        run: echo "This is a log message ${{ secrets.SSH_SERVER_HOST }}"

      - name: Install dependencies
        run: npm install

      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{secrets.PASSWORD}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /apps/test/actionsPractice
            npm start
            # Add any other necessary deployment commands test_1.8
