name: Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log Message host
        run: echo "This is a log message ${{ secrets.SSH_SERVER_HOST }}"

      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: 137.184.137.85
          username: root
          passphrase: qbatch
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            whoami
            cd apps/test/actionsPractice
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            echo "Node version is $(node -v)"
            echo "Npm version is $(npm -v)"
            npm start
            # Add any other necessary deployment commands test_1.9
